name: .NET 9 CI

env:
  PROJECT_NAME: 'BarlogM-Andern'

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: |
          cd ${{ env.PROJECT_NAME }}
          dotnet build --configuration Release --output ${{ env.PROJECT_NAME }}

      - name: Create zip archive
        run: |
          cd ${{ env.PROJECT_NAME }}
          mkdir -p SPT/user/mods
          mv ${{ env.PROJECT_NAME }} SPT/user/mods/
          zip -r ${{ env.PROJECT_NAME }}.zip SPT/user/mods/${{ env.PROJECT_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
